### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by codemonies** [Xxx-Bin/php-ja3#1]
Hello,

The current version doesn't contain some important fields like the demo version: https://bjun.tech:9763/demo/ja3/ja3.php

Specifically:
- ja3t_hash
- ja3_str

Could you please update the Git?

Thank you so much!

**Comment by Xxx-Bin** [comment]
```
  if(!empty($ja3['session_ticket'])){
        $_SESSION['ja3t_hash'] = $ja3['ja3'];
    }else{
        $_SESSION['ja3_hash'] = $ja3['ja3'];
    }
    echo json_encode([
        'ja3t_hash' => empty($_SESSION['ja3t_hash']) ? '' : $_SESSION['ja3t_hash'],
        'ja3_hash' => empty($_SESSION['ja3_hash']) ? '' : $_SESSION['ja3_hash'],
        'ja3_str' => empty($ja3['ja3_str']) ? '' : $ja3['ja3_str'],
    ]);

```


Note that in [ja3_tcpdump.php](https://github.com/Xxx-Bin/php-ja3/blob/main/ja3_tcpdump.php), ja3t_ Hash is invalid because handshake data with session_ticket is not caught

**Comment by codemonies** [comment]
Thank you for the quick response.

However, in [ja3_tcpdump.php](https://github.com/Xxx-Bin/php-ja3/blob/main/ja3_tcpdump.php), there is no mention of ja3t_

When I access your script [here](https://bjun.tech:9763/demo/ja3/ja3.php), it gives this output:
`{"ja3t_hash":"1c15aca4a38bad90f9c40678f6aface9","ja3_hash":"2c3efc25fa24d4f1f973fc059207ccda","ja3_str":"771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49171-49172-47-53-10,0-23-65281-10-11-35-16-5-40-43-13-45,29-23-24-25-256-257,0"}`

When I acess it on my own domain with the above modification, it gives this:
`{"ja3t_hash":"1c15aca4a38bad90f9c40678f6aface9","ja3_hash":"","ja3_str":"771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49171-49172-47-53-10,0-23-65281-10-11-35-16-5-40-43-13-45,29-23-24-25-256-257,0"}`

When I check [here](https://tlshello.agwa.name/), it gives the same JA3 as your ja3_hash value, so I believe that's what should be relied on.

Can you recheck if the GIt is up-to-date with your demo version?

Thank you very much!

**Comment by Xxx-Bin** [comment]
I'm not sure if I can explain the problem clearly. Ja3t is a value defined by myself. In some cases, the TLS session resumption or other reasons will cause ja3 to change. According to the definition of ja3, it should only be the first handshake, but it is difficult to trigger and reproduce the conditions. Whether ja3t is meaningful is also debatable. There are several ways to feel the process. For example, privacy mode can be passed again chrome://net-internals/#sockets Close sockets

In addition, the demo code version is consistent with GitHub. The difference is that there are two demo versions.

tcpdump : https://ja3.bjun.tech/ja3.php

wkm: https://bjun.tech:9763/demo/ja3/ja3.php

**Comment by natesreich** [comment]
Thank you, that explains a lot.

The problem for me is, only tcpdump seems to work. On my server, when I use wkm, the response from ja.php is always "none" (even after flushing the sockets in Chrome).

You can see here that wkm_ja3.php was started properly: 
![putty_2022-06-06_04-12-29](https://user-images.githubusercontent.com/13593587/172122329-d4daafa2-ba22-4d9c-82c5-df77a09e6257.png)

I didn't modify anything in wkm_ja3.php:
![notepad++_2022-06-06_04-14-22](https://user-images.githubusercontent.com/13593587/172122508-c24d9911-4e72-4640-924e-dd15af7b6cb3.png)

Any ideas why the response would always be "none"?

**Comment by codemonies** [comment]
Thank you, that explains a lot.

**Comment by Xxx-Bin** [comment]
Wkm is different from tcpdump.  You need set your domain here.
```
define('OUTBOUND','tcp://example.com:443');
```
Wkm‘s Data link like this.Correct configuration is required for normal traffic transmission.
```
brower => php-ja3(INBOUND) => catch JA3 => php-ja3(OUTBOUND) => nginx(https=>http) => /web/ja3.php
```
In addition, you need to make sure that the firewall works normally. If you use PHP FPM, you also need to ensure that it works normally

**Comment by codemonies** [comment]
Yep, I got it working shortly after that post.

Thank you very much!

**Comment by Xxx-Bin** [comment]
https://ja3.bjun.tech/ja3.php return none can see https://bjun.tech/blog/xphp/144#demo_48. 
The reason is only the first handshake can catch ja3 in tcpdump.

**Comment by codemonies** [comment]
Got it.

The problem with using tcpdump then is that its Ja3 can't be reliably used for fingerprinting. After all, if a refresh changes the Ja3 (no longer the first handshake), then it's a bit useless.

On the other hand, the "ja3_hash" value when using wkm on your demo always seems to be fixed, so that's good.

The problem I am encountering on my server is that after the first refresh, only the changed "ja3t_hash" value exists but "ja3_hash" is always empty.

Chrome:
`{"ja3t_hash":"cd08e31494f9531f560d64c695473da9","ja3_hash":"","ja3_str":"771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-17513-21,29-23-24,0"}`

Firefox:
`{"ja3t_hash":"1c15aca4a38bad90f9c40678f6aface9","ja3_hash":"","ja3_str":"771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49171-49172-47-53-10,0-23-65281-10-11-35-16-5-40-43-13-45,29-23-24-25-256-257,0"}`

However, on your server the "ja3t_hash" and "ja3_hash" values are always specified on subsequent refreshes. The "ja3_hash" value is the one that is not changing after refreshes on wkm, so I think that's what is important.

I just have to figure out why it is empty after refresh on my server, when on your demo it's fine.

**Comment by Xxx-Bin** [comment]
In wkm ,I  use session to save the ja3 .The code I had shared first.
https://github.com/Xxx-Bin/php-ja3/issues/1#issuecomment-1146753415

This project focuses on got ja3 .How to save or keep it available is other question. Http session just one way .In tcpdump ,this way was effective.
If you are interested, you can follow TLS seesion ticket, which is also an important information for establishing contact. But I haven't paid much attention to it at present

**Comment by Xxx-Bin** [comment]
The reason ja3_hash  is empty ,your request was not the fisrt handshake.In my demo, after delete the cookie you can see the same result.

**Comment by codemonies** [comment]
Understood.

However, the purpose of Ja3 is to be able to fingerprint and block requests. If the visitor can just clear sessions, or refresh the page and have a different Ja3 value, then it can't reliably be used. The ja3s value seems to be inconsistent as well.

On this website though, the Ja3 value is always consistent: https://tlshello.agwa.name/

**Comment by Xxx-Bin** [comment]
Even if ja3 will change, it will only have two values, and its characteristics are obvious. The server can close the TLS session for recovery. Maybe they have made this setting.
Ja3s is a server fingerprint, which we usually don't use.
For purpose, if you do not have an additional proxy or specify a browser, the fingerprint is chromium's Most websites will not ban this browser

**Comment by codemonies** [comment]
> The server can close the TLS session for recovery. Maybe they have made this setting.
I think this will be necessary. Otherwise, we will not be able to block bad Ja3 on the first request.

According to [workerman](https://github.com/walkor/workerman/issues/580), the connection can be closed using $connection->close();

Do you have any idea how this can be added to wkm_ja3.php so that it closes the TCP connection after each response?

I tried it like this, but I get "the connection was interrupted" when I load ja3.php after:
![notepad++_2022-06-06_17-08-03](https://user-images.githubusercontent.com/13593587/172249724-cb5bfc56-8052-4456-91db-9108c4e4026b.png)

**Comment by Xxx-Bin** [comment]
see https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_session_tickets

**Comment by Xxx-Bin** [comment]
This is beyond my ability. Closing sessionticket seems to be against my expectations. I don't understand for the time being.

**Comment by codemonies** [comment]
> see https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_session_tickets

This worked perfectly. Now the ja3_hash is being maintained as intended.

Thank you very much!
